### PR TITLE
Pid id messages

### PR DESCRIPTION
**Pull request by tallakt**
This is tested to work on my machine. It adds an extra option to get pids instead of serial port names in active mode.

### CODE REVIEW

**Comment by fhunleth** [comment]
Thanks! I merged it manually so that I could fix a couple really minor typos.

**Comment by fhunleth** [comment]
I'll plan to make a new hex.pm release soon to make this generally available.

**Comment by tallakt** [comment]
Thanks. Always fun to be able to contribute.

**Comment by tallakt** [comment]
Your changes were pure improvement btw. Thanks

**Pull request closed without merging**
